development:
  adapter: postgresql
  encoding: utf8
  database: usingfoodwaste_development
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: utf8
  database: usingfoodwaste_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: usingfoodwaste_production
  pool: 5
  username:
  password:

cucumber:
  <<: *test
